### ISSUE TITLE
TypeError: Cannot read property 'coords' of null

### ISSUE THREAD

**Issue by garyee** [garyee/historienpfad#1]
It's probably due to google maps currrent implementation.

TypeError: Cannot read property 'coords' of null at http://localhost:8100/build/main.js:745:42 at http://localhost:8100/build/vendor.js:137258:13 at t.invoke (http://localhost:8100/build/polyfills.js:3:14976) at Object.onInvoke (http://localhost:8100/build/vendor.js:5134:33) at t.invoke (http://localhost:8100/build/polyfills.js:3:14916) at r.runGuarded (http://localhost:8100/build/polyfills.js:3:10346) at http://localhost:8100/build/polyfills.js:3:9958

**Comment by garyee** [comment]
ported to jira
